### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by andresBelAlonso** [sirolf2009/fxgraph#4]
Hey, 
In the repository the license file is a WTFPL, but in the pom.xml file (line 79) the license is GPL : 

```
	<licenses>
		<license>
			<name>GNU General Public License v3.0</name>
			<url>https://www.gnu.org/licenses/gpl-3.0.en.html</url>
			<distribution>repo</distribution>
		</license>
	</licenses>
```
What is the right license? Or the code is under both licenses?
Thanks!

**Comment by andresBelAlonso** [comment]
I have been looking in this question, and the base job using code from StackOverflow means using code licensed under Creative Commons Attribution-ShareAlike 4.0 license ( https://stackoverflow.com/help/licensing). 
But this license is compatible with a GPL v3 license (https://creativecommons.org/share-your-work/licensing-considerations/compatible-licenses), so it is possible to change the license from Creative Commons Attribution-ShareAlike 4.0 to GPL v3.

**Comment by andresBelAlonso** [comment]
To use another license than GPLv3 license, or Creative Commons Attribution-ShareAlike 4.0 license, @Roland09 should edit his original StackOverflow answer ( https://stackoverflow.com/questions/30679025/graph-visualisation-like-yfiles-in-javafx ) to license the code in his answer. 
@Roland09 can you please edit the answer to license the code of the answer under a non copyleft license (like MIT license...)? 
@sirolf2009 If Roland changes his license, can you update the license of your works to be compatible with the Roland one.
The code of the StackOverflow answer and this library are used by many other libraries, it will be nice to fix this legal issue!

**Comment by Roland09** [comment]
@andresBelAlonso i wasn't aware that i should / could do any licensing with a stackoverflow answer, never seen that before. feel free to use the code of my answer as you see fit.

**Comment by sirolf2009** [comment]
Woops, nicely spotted. I've updated the license in the pom.xml to WFTPL
